version: '3.8'

services:
  # =====================
  # 数据库服务（MySQL）
  # =====================
  mysql:
    image: mysql:8.0
    container_name: coding-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: codingtracker
      MYSQL_USER: tracker_user
      MYSQL_PASSWORD: tracker_pass
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # =====================
  # 后端服务（Spring Boot）
  # =====================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: coding-backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "9090:8080"  # 将容器的8080端口映射到宿主机的9090端口
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/codingtracker?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: tracker_user
      SPRING_DATASOURCE_PASSWORD: tracker_pass

  # =====================
  # 前端服务（Vue）
  # =====================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: coding-frontend
    restart: always
    ports:
      - "411:80"
    depends_on:
      - backend
    environment:
      VUE_APP_BASE_API: http://119.45.10.196:9090  # 生产环境需要替换为实际服务器的 IP 地址或域名
      ENV: production  # 可根据需要设置的其他环境变量

volumes:
  mysql_data:
    driver: local
